"""outreach/constants.py

Central place for outreach module keys + string permissions.
Outreach permissions are stored on OutreachStaffProfile.permissions (JSON list).

Design:
- Module toggle checks rely on module keys (strings).
- Permission checks rely on permission keys (strings).
"""

# Module keys (patients is implicit / always available)
MODULE_VITALS = "vitals"
MODULE_ENCOUNTER = "encounter"
MODULE_LAB = "lab"
MODULE_PHARMACY = "pharmacy"
MODULE_IMMUNIZATION = "immunization"
MODULE_BLOOD_DONATION = "blood_donation"
MODULE_COUNSELING = "counseling"
MODULE_MATERNAL = "maternal"

MODULE_REFERRAL = "referral"
MODULE_SURGICALS = "surgicals"
MODULE_EYE_CHECKS = "eye_checks"
MODULE_DENTAL_CHECKS = "dental_checks"

ALL_OPTIONAL_MODULES = {
    MODULE_VITALS,
    MODULE_ENCOUNTER,
    MODULE_LAB,
    MODULE_PHARMACY,
    MODULE_IMMUNIZATION,
    MODULE_BLOOD_DONATION,
    MODULE_COUNSELING,
    MODULE_MATERNAL,
    MODULE_REFERRAL,
    MODULE_SURGICALS,
    MODULE_EYE_CHECKS,
    MODULE_DENTAL_CHECKS,
}

# Permission keys
# Patients
PERM_PATIENTS_VIEW = "patients.view"
PERM_PATIENTS_CREATE = "patients.create"
PERM_PATIENTS_EDIT = "patients.edit"

# Vitals
PERM_VITALS_CREATE = "vitals.create"
PERM_VITALS_EDIT = "vitals.edit"

# Encounter
PERM_ENCOUNTER_CREATE = "encounter.create"
PERM_ENCOUNTER_EDIT = "encounter.edit"

# Lab
PERM_LAB_CATALOG_VIEW = "lab.catalog.view"
PERM_LAB_CATALOG_MANAGE = "lab.catalog.manage"
PERM_LAB_ORDER_CREATE = "lab.order.create"
PERM_LAB_ORDER_EDIT = "lab.order.edit"
PERM_LAB_RESULT_CREATE = "lab.result.create"
PERM_LAB_RESULT_EDIT = "lab.result.edit"

# Pharmacy
PERM_PHARMACY_CATALOG_VIEW = "pharmacy.catalog.view"
PERM_PHARMACY_CATALOG_MANAGE = "pharmacy.catalog.manage"
PERM_PHARMACY_DISPENSE_CREATE = "pharmacy.dispense.create"
PERM_PHARMACY_DISPENSE_EDIT = "pharmacy.dispense.edit"

# Immunization
PERM_IMMUNIZATION_CREATE = "immunization.create"
PERM_IMMUNIZATION_EDIT = "immunization.edit"

# Blood donation
PERM_BLOOD_CREATE = "blood_donation.create"
PERM_BLOOD_EDIT = "blood_donation.edit"

# Counseling
PERM_COUNSELING_CREATE = "counseling.create"
PERM_COUNSELING_EDIT = "counseling.edit"
PERM_COUNSELING_VIEW_SENSITIVE = "counseling.view_sensitive"

# Maternal
PERM_MATERNAL_CREATE = "maternal.create"
PERM_MATERNAL_EDIT = "maternal.edit"

# Referral
PERM_REFERRAL_CREATE = "referral.create"
PERM_REFERRAL_EDIT = "referral.edit"

# Surgicals
PERM_SURGICALS_CREATE = "surgicals.create"
PERM_SURGICALS_EDIT = "surgicals.edit"

# Eye checks
PERM_EYE_CHECKS_CREATE = "eye_checks.create"
PERM_EYE_CHECKS_EDIT = "eye_checks.edit"

# Dental checks
PERM_DENTAL_CHECKS_CREATE = "dental_checks.create"
PERM_DENTAL_CHECKS_EDIT = "dental_checks.edit"

# Reports
PERM_REPORTS_VIEW = "reports.view"
PERM_REPORTS_EXPORT = "reports.export"

ALL_PERMISSIONS = {
    PERM_PATIENTS_VIEW, PERM_PATIENTS_CREATE, PERM_PATIENTS_EDIT,
    PERM_VITALS_CREATE, PERM_VITALS_EDIT,
    PERM_ENCOUNTER_CREATE, PERM_ENCOUNTER_EDIT,
    PERM_LAB_CATALOG_VIEW, PERM_LAB_CATALOG_MANAGE, PERM_LAB_ORDER_CREATE, PERM_LAB_ORDER_EDIT,
    PERM_LAB_RESULT_CREATE, PERM_LAB_RESULT_EDIT,
    PERM_PHARMACY_CATALOG_VIEW, PERM_PHARMACY_CATALOG_MANAGE,
    PERM_PHARMACY_DISPENSE_CREATE, PERM_PHARMACY_DISPENSE_EDIT,
    PERM_IMMUNIZATION_CREATE, PERM_IMMUNIZATION_EDIT,
    PERM_BLOOD_CREATE, PERM_BLOOD_EDIT,
    PERM_COUNSELING_CREATE, PERM_COUNSELING_EDIT, PERM_COUNSELING_VIEW_SENSITIVE,
    PERM_MATERNAL_CREATE, PERM_MATERNAL_EDIT,
    PERM_REFERRAL_CREATE, PERM_REFERRAL_EDIT,
    PERM_SURGICALS_CREATE, PERM_SURGICALS_EDIT,
    PERM_EYE_CHECKS_CREATE, PERM_EYE_CHECKS_EDIT,
    PERM_DENTAL_CHECKS_CREATE, PERM_DENTAL_CHECKS_EDIT,
    PERM_REPORTS_VIEW, PERM_REPORTS_EXPORT,
}

# Role templates (defaults). OSA can override by selecting permissions manually.
ROLE_REGISTRATION = "REGISTRATION"
ROLE_VITALS = "NURSE_VITALS"
ROLE_CLINICIAN = "CLINICIAN"
ROLE_LAB = "LAB"
ROLE_PHARMACY = "PHARMACY"
ROLE_IMMUNIZATION = "IMMUNIZATION"
ROLE_BLOOD_DONATION = "BLOOD_DONATION"
ROLE_COUNSELOR = "COUNSELOR"
ROLE_MATERNAL = "MATERNAL"
ROLE_AUDITOR = "AUDITOR"
ROLE_CUSTOM = "CUSTOM"

ROLE_TEMPLATES = {
    ROLE_REGISTRATION: {PERM_PATIENTS_VIEW, PERM_PATIENTS_CREATE, PERM_PATIENTS_EDIT},
    ROLE_VITALS: {PERM_PATIENTS_VIEW, PERM_VITALS_CREATE, PERM_VITALS_EDIT},
    ROLE_CLINICIAN: {
        PERM_PATIENTS_VIEW,
        PERM_VITALS_CREATE, PERM_VITALS_EDIT,
        PERM_ENCOUNTER_CREATE, PERM_ENCOUNTER_EDIT,
        PERM_LAB_CATALOG_VIEW, PERM_LAB_ORDER_CREATE, PERM_LAB_RESULT_CREATE,
        PERM_PHARMACY_CATALOG_VIEW, PERM_PHARMACY_DISPENSE_CREATE,
        PERM_IMMUNIZATION_CREATE,
        PERM_MATERNAL_CREATE,
        PERM_REFERRAL_CREATE, PERM_REFERRAL_EDIT,
        PERM_SURGICALS_CREATE, PERM_SURGICALS_EDIT,
        PERM_EYE_CHECKS_CREATE, PERM_EYE_CHECKS_EDIT,
        PERM_DENTAL_CHECKS_CREATE, PERM_DENTAL_CHECKS_EDIT,
    },
    ROLE_LAB: {
        PERM_PATIENTS_VIEW,
        PERM_LAB_CATALOG_VIEW, PERM_LAB_CATALOG_MANAGE,
        PERM_LAB_ORDER_CREATE, PERM_LAB_ORDER_EDIT,
        PERM_LAB_RESULT_CREATE, PERM_LAB_RESULT_EDIT,
    },
    ROLE_PHARMACY: {
        PERM_PATIENTS_VIEW,
        PERM_PHARMACY_CATALOG_VIEW, PERM_PHARMACY_CATALOG_MANAGE,
        PERM_PHARMACY_DISPENSE_CREATE, PERM_PHARMACY_DISPENSE_EDIT,
    },
    ROLE_IMMUNIZATION: {PERM_PATIENTS_VIEW, PERM_VITALS_CREATE, PERM_IMMUNIZATION_CREATE, PERM_IMMUNIZATION_EDIT},
    ROLE_BLOOD_DONATION: {PERM_PATIENTS_VIEW, PERM_BLOOD_CREATE, PERM_BLOOD_EDIT},
    ROLE_COUNSELOR: {PERM_PATIENTS_VIEW, PERM_COUNSELING_CREATE, PERM_COUNSELING_EDIT, PERM_COUNSELING_VIEW_SENSITIVE},
    ROLE_MATERNAL: {PERM_PATIENTS_VIEW, PERM_VITALS_CREATE, PERM_MATERNAL_CREATE, PERM_MATERNAL_EDIT},
    ROLE_AUDITOR: {PERM_PATIENTS_VIEW, PERM_REPORTS_VIEW},
    ROLE_CUSTOM: set(),
}

# Map outreach role templates to accounts.UserRole (best-effort)
OUTREACH_ROLE_TO_ACCOUNT_ROLE = {
    ROLE_REGISTRATION: "FRONTDESK",
    ROLE_VITALS: "NURSE",
    ROLE_CLINICIAN: "DOCTOR",
    ROLE_LAB: "LAB",
    ROLE_PHARMACY: "PHARMACY",
    ROLE_IMMUNIZATION: "NURSE",
    ROLE_BLOOD_DONATION: "NURSE",
    ROLE_COUNSELOR: "NURSE",
    ROLE_MATERNAL: "NURSE",
    ROLE_AUDITOR: "ADMIN",
    ROLE_CUSTOM: "ADMIN",
}
