# Generated by Django 5.2.7 on 2025-10-15 12:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('modality', models.CharField(choices=[('XR', 'X-Ray'), ('US', 'Ultrasound'), ('CT', 'CT'), ('MRI', 'MRI')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_reports_authored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=32)),
                ('file', models.FileField(upload_to='imaging_assets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='imaging.imagingreport')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'Stat')], default='ROUTINE', max_length=12)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('REPORTED', 'Reported'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=12)),
                ('indication', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('encounter_id', models.PositiveIntegerField(blank=True, null=True)),
                ('external_center_name', models.CharField(blank=True, max_length=160)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_requests', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_requests', to='patients.patient')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imaging.imagingprocedure')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='imagingreport',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='imaging.imagingrequest'),
        ),
        migrations.AddIndex(
            model_name='imagingrequest',
            index=models.Index(fields=['patient', 'requested_at'], name='imaging_ima_patient_313f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingrequest',
            index=models.Index(fields=['facility', 'requested_at'], name='imaging_ima_facilit_93ba29_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingrequest',
            index=models.Index(fields=['status'], name='imaging_ima_status_d99cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingrequest',
            index=models.Index(fields=['procedure'], name='imaging_ima_procedu_64bace_idx'),
        ),
    ]
