# Generated by Django 5.2.7 on 2025-12-27 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('facilities', '0006_bedassignment'),
        ('patients', '0007_patientproviderlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='charge',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='price',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charge',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='price',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='facilities.facility'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['owner', 'created_at'], name='billing_cha_owner_i_a0d741_idx'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('facility__isnull', False), ('owner__isnull', True)), models.Q(('facility__isnull', True), ('owner__isnull', False)), _connector='OR'), name='billing_charge_scope_xor'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('facility__isnull', False), ('owner__isnull', True)), models.Q(('facility__isnull', True), ('owner__isnull', False)), _connector='OR'), name='billing_payment_scope_xor'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('facility__isnull', False), ('owner__isnull', True)), models.Q(('facility__isnull', True), ('owner__isnull', False)), _connector='OR'), name='billing_price_scope_xor'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False), ('owner__isnull', True)), fields=('facility', 'service'), name='billing_price_unique_facility_service'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', True), ('owner__isnull', False)), fields=('owner', 'service'), name='billing_price_unique_owner_service'),
        ),
    ]
