# Generated by Django 5.2.7 on 2025-12-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_price_unique_together_charge_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('POS', 'POS'), ('TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], default='CASH', max_length=16),
        ),
    ]
