# Generated by Django 5.2.7 on 2026-01-03 23:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_payment_method'),
        ('facilities', '0006_bedassignment'),
        ('patients', '0007_patientproviderlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HMOPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hmo_prices', to='facilities.facility')),
                ('hmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='patients.hmo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.service')),
            ],
            options={
                'ordering': ['service__code'],
                'constraints': [models.UniqueConstraint(fields=('facility', 'hmo', 'service'), name='uniq_hmo_price_per_service')],
            },
        ),
    ]
