# Generated by Django 5.2.7 on 2026-01-05 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_service_created_at_service_updated_at_hmoprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
