# Generated by Django 5.2.7 on 2026-01-08 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_service_default_price'),
        ('facilities', '0007_facilityrolepermission'),
        ('patients', '0010_hmo_addresses_hmo_contact_numbers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hmo',
            field=models.ForeignKey(blank=True, help_text='Set for HMO bulk payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='patients.hmo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_source',
            field=models.CharField(choices=[('PATIENT_DIRECT', 'Patient Direct Payment'), ('HMO', 'HMO Payment'), ('INSURANCE', 'Insurance Payment'), ('CORPORATE', 'Corporate Payment'), ('OTHER', 'Other')], default='PATIENT_DIRECT', help_text='Source of the payment', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='period_end',
            field=models.DateField(blank=True, help_text='End of billing period for HMO bulk payments', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start of billing period for HMO bulk payments', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Receipt number, transaction ID, etc.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hmo', '-received_at'], name='billing_pay_hmo_id_f9d251_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_source', '-received_at'], name='billing_pay_payment_1ddfd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('patient__isnull', False), ('hmo__isnull', False), _connector='OR'), name='billing_payment_patient_or_hmo'),
        ),
    ]
