# Generated by Django 5.2.7 on 2026-01-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_payment_hmo_payment_payment_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hmoprice',
            options={'ordering': ['service__code'], 'verbose_name': 'HMO Price', 'verbose_name_plural': 'HMO Prices'},
        ),
        migrations.RemoveConstraint(
            model_name='hmoprice',
            name='uniq_hmo_price_per_service',
        ),
        migrations.RemoveField(
            model_name='hmoprice',
            name='hmo',
        ),
        migrations.AddField(
            model_name='hmoprice',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Independent provider who set this price', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hmo_prices', to=settings.AUTH_USER_MODEL),
        ),
    ]
