# Generated by Django 5.2.7 on 2026-01-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_hmoprice_options_and_more'),
        ('facilities', '0008_facility_is_publicly_visible'),
        ('patients', '0012_hmotier_systemhmo_patient_hmo_enrolled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hmoprice',
            name='system_hmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='patients.systemhmo'),
        ),
        migrations.AddField(
            model_name='hmoprice',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='If set, this price only applies to this specific tier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='patients.hmotier'),
        ),
        migrations.AlterField(
            model_name='hmoprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmo_prices', to='billing.service'),
        ),
        migrations.AddIndex(
            model_name='hmoprice',
            index=models.Index(fields=['facility', 'system_hmo', 'service'], name='billing_hmo_facilit_9a5f38_idx'),
        ),
        migrations.AddIndex(
            model_name='hmoprice',
            index=models.Index(fields=['owner', 'system_hmo', 'service'], name='billing_hmo_owner_i_0a8110_idx'),
        ),
        migrations.AddIndex(
            model_name='hmoprice',
            index=models.Index(fields=['system_hmo', 'tier', 'service'], name='billing_hmo_system__7de094_idx'),
        ),
        migrations.AddConstraint(
            model_name='hmoprice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('facility__isnull', False), ('owner__isnull', True)), models.Q(('facility__isnull', True), ('owner__isnull', False)), _connector='OR'), name='billing_hmo_price_scope_xor'),
        ),
        migrations.AddConstraint(
            model_name='hmoprice',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False)), fields=('facility', 'system_hmo', 'tier', 'service'), name='unique_facility_hmo_tier_service_price'),
        ),
        migrations.AddConstraint(
            model_name='hmoprice',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'system_hmo', 'tier', 'service'), name='unique_owner_hmo_tier_service_price'),
        ),
    ]
