# Generated by Django 5.2.7 on 2026-01-16 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_hmoprice_system_hmo_hmoprice_tier_and_more'),
        ('patients', '0012_hmotier_systemhmo_patient_hmo_enrolled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmoprice',
            name='system_hmo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='patients.systemhmo'),
        ),
    ]
