# Generated by Django 5.2.7 on 2026-01-25 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_hmoprice_system_hmo'),
        ('facilities', '0008_facility_is_publicly_visible'),
        ('patients', '0013_facilityhmo_addresses_facilityhmo_contact_numbers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='billing_payment_patient_or_hmo',
        ),
        migrations.AddField(
            model_name='payment',
            name='facility_hmo',
            field=models.ForeignKey(blank=True, help_text='Facility/Provider HMO relationship for bulk payments (recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='patients.facilityhmo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='system_hmo',
            field=models.ForeignKey(blank=True, help_text='System HMO for bulk payments (new system-scoped HMO).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='patients.systemhmo'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['system_hmo', '-received_at'], name='billing_pay_system__02d038_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['facility_hmo', '-received_at'], name='billing_pay_facilit_d402ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('patient__isnull', False), ('hmo__isnull', False), ('system_hmo__isnull', False), ('facility_hmo__isnull', False), _connector='OR'), name='billing_payment_patient_or_hmo'),
        ),
    ]
