# Generated by Django 5.2.7 on 2025-10-15 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_type', models.CharField(choices=[('NEW', 'New'), ('FOLLOW_UP', 'Follow-up'), ('VIRTUAL', 'Virtual')], default='NEW', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'Stat')], default='ROUTINE', max_length=16)),
                ('occurred_at', models.DateTimeField(help_text='When the encounter took place')),
                ('chief_complaint', models.TextField(blank=True)),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, max_length=16)),
                ('hpi', models.TextField(blank=True)),
                ('ros', models.TextField(blank=True)),
                ('physical_exam', models.TextField(blank=True)),
                ('diagnoses', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('lab_order_ids', models.JSONField(blank=True, default=list)),
                ('imaging_request_ids', models.JSONField(blank=True, default=list)),
                ('prescription_ids', models.JSONField(blank=True, default=list)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EncounterAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='encounters.encounter')),
            ],
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'occurred_at'], name='encounters__patient_5da0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['facility', 'occurred_at'], name='encounters__facilit_9ad572_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status'], name='encounters__status_d58071_idx'),
        ),
    ]
