# Generated by Django 5.2.7 on 2025-10-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CROSSED_OUT', 'Crossed Out')], default='OPEN', max_length=16),
        ),
    ]
