# Generated by Django 5.2.7 on 2025-12-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_encounter_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounteramendment',
            name='section',
            field=models.CharField(blank=True, choices=[('CHIEF_COMPLAINT', 'Chief complaint'), ('HPI', 'History (HPI)'), ('ROS', 'Review of systems'), ('PHYSICAL_EXAM', 'Physical exam'), ('DIAGNOSES', 'Diagnoses'), ('PLAN', 'Plan')], default='', help_text='SOAP note section being corrected (required for per-section corrections).', max_length=32),
        ),
    ]
