# Generated by Django 5.2.7 on 2025-12-20 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_encounteramendment_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='nurse',
            field=models.ForeignKey(blank=True, help_text='Nurse who initiated the encounter and recorded vitals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_as_nurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Doctor or clinical provider responsible for diagnosis and treatment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_as_provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
