# Generated by Django 5.2.7 on 2025-12-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0005_encounter_nurse_encounter_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounteramendment',
            name='amendment_type',
            field=models.CharField(choices=[('CORRECTION', 'Correction'), ('ADDITION', 'Addition')], default='CORRECTION', help_text='Type of amendment: correction replaces, addition supplements', max_length=16),
        ),
    ]
