# Generated by Django 5.2.7 on 2025-10-15 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('DOCTOR', 'Medical Doctor'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('LAB_SCIENTIST', 'Medical Lab Scientist'), ('DENTIST', 'Dentist'), ('OPTOMETRIST', 'Optometrist'), ('PHYSIOTHERAPIST', 'Physiotherapist'), ('OTHER', 'Other')], default='DOCTOR', max_length=24)),
                ('license_council', models.CharField(choices=[('MDCN', 'Medical & Dental Council'), ('NMCN', 'Nursing & Midwifery Council'), ('PCN', 'Pharmacists Council'), ('MLSCN', 'Med. Lab. Science Council'), ('RADI', 'Radiographers Board'), ('OTHER', 'Other')], default='MDCN', max_length=16)),
                ('license_number', models.CharField(max_length=64)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('years_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must be E.164 format (e.g. +2348012345678).', regex='^\\+\\d{1,3}\\d{6,14}$')])),
                ('country', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('lga', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialties', models.ManyToManyField(blank=True, related_name='providers', to='facilities.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(upload_to='provider_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='providers.providerprofile')),
            ],
        ),
    ]
