# Generated by Django 5.2.7 on 2026-01-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providerfacilityapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='business_name',
            field=models.CharField(blank=True, help_text="Business/practice name for independent providers (e.g., 'City Medical Lab', 'Downtown Pharmacy')", max_length=255),
        ),
    ]
