# Generated by Django 5.2.7 on 2026-01-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_providerprofile_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='is_publicly_visible',
            field=models.BooleanField(default=True, help_text='Controls whether this provider appears in public search and can accept online bookings'),
        ),
    ]
