# Generated by Django 5.2.7 on 2025-10-15 09:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('EYE_CLINIC', 'Eye Clinic'), ('DENTAL_CLINIC', 'Dental Clinic'), ('IMAGING_CENTER', 'Imaging & Diagnostic Center'), ('LABORATORY', 'Laboratory'), ('SOLO_PRACTICE', 'Solo Practice'), ('AMBULATORY_CENTER', 'Ambulatory Surgical Center'), ('OTHER', 'Other')], default='HOSPITAL', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('controlled_by', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('lga', models.CharField(max_length=120, verbose_name='Local Govt Area')),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(help_text='E.164 format', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must be E.164 format (e.g. +2348012345678).', regex='^\\+\\d{1,3}\\d{6,14}$')])),
                ('nhis_approved', models.BooleanField(default=False)),
                ('nhis_number', models.CharField(blank=True, max_length=120)),
                ('total_bed_capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhis_certificate', models.FileField(blank=True, upload_to='facility_docs/')),
                ('md_practice_license', models.FileField(blank=True, upload_to='facility_docs/')),
                ('state_registration_cert', models.FileField(blank=True, upload_to='facility_docs/')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityExtraDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Other', max_length=120)),
                ('file', models.FileField(upload_to='facility_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_docs', to='facilities.facility')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='facilities.specialty'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='facilities.facility')),
            ],
            options={
                'unique_together': {('facility', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('is_available', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='facilities.ward')),
            ],
            options={
                'unique_together': {('ward', 'number')},
            },
        ),
    ]
