# Generated by Django 5.2.7 on 2025-10-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='controlled_by',
            field=models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('church', 'Church'), ('ngo', 'NGO'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
