# Generated by Django 5.2.7 on 2025-10-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_country_alter_facility_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='state',
            field=models.CharField(blank=True, choices=[('---nigeria---', '--- Nigeria ---'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara'), ('fct', 'FCT - Abuja'), ('---ghana---', '--- Ghana ---'), ('ashanti', 'Ashanti'), ('brong_ahafo', 'Brong-Ahafo'), ('central', 'Central'), ('eastern', 'Eastern'), ('greater_accra', 'Greater Accra'), ('northern', 'Northern'), ('savannah', 'Savannah'), ('upper_east', 'Upper East'), ('upper_west', 'Upper West'), ('volta', 'Volta'), ('western', 'Western'), ('western_north', 'Western North'), ('---kenya---', '--- Kenya ---'), ('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('machakos', 'Machakos'), ('nyeri', 'Nyeri'), ('kisii', 'Kisii'), ('muranga', "Murang'a"), ('garissa', 'Garissa'), ('lamu', 'Lamu'), ('marsabit', 'Marsabit'), ('kilifi', 'Kilifi'), ('bomet', 'Bomet'), ('turkana', 'Turkana'), ('---south_africa---', '--- South Africa ---'), ('eastern_cape', 'Eastern Cape'), ('free_state', 'Free State'), ('gauteng', 'Gauteng'), ('kwazulu_natal', 'KwaZulu-Natal'), ('limpopo', 'Limpopo'), ('mpumalanga', 'Mpumalanga'), ('northern_cape', 'Northern Cape'), ('north_west', 'North West'), ('western_cape', 'Western Cape')], max_length=50, null=True),
        ),
    ]
