# Generated by Django 5.2.7 on 2025-12-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_alter_facility_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['ward__name', 'number']},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_class',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SEMI_PRIVATE', 'Semi-private'), ('PRIVATE', 'Private')], default='GENERAL', max_length=32),
        ),
        migrations.AddField(
            model_name='bed',
            name='has_monitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bed',
            name='has_oxygen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bed',
            name='is_operational',
            field=models.BooleanField(default=True, help_text='Set to false if this bed cannot be used (faulty, blocked, etc).'),
        ),
        migrations.AddField(
            model_name='bed',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning'), ('OUT_OF_SERVICE', 'Out of service')], default='AVAILABLE', max_length=32),
        ),
        migrations.AddField(
            model_name='ward',
            name='floor',
            field=models.CharField(blank=True, help_text="Optional floor or block label (e.g. 'Ground', '1st floor').", max_length=64),
        ),
        migrations.AddField(
            model_name='ward',
            name='gender_policy',
            field=models.CharField(choices=[('MIXED', 'Mixed'), ('MALE_ONLY', 'Male only'), ('FEMALE_ONLY', 'Female only')], default='MIXED', max_length=32),
        ),
        migrations.AddField(
            model_name='ward',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ICU', 'ICU'), ('PICU', 'Pediatric ICU'), ('NICU', 'Neonatal ICU'), ('MATERNITY', 'Maternity'), ('ISOLATION', 'Isolation')], default='GENERAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='bed',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
