# Generated by Django 5.2.7 on 2025-12-12 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_alter_encounter_status'),
        ('facilities', '0005_alter_bed_options_alter_ward_options_bed_bed_class_and_more'),
        ('patients', '0005_alter_patientdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='facilities.bed')),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_assignments_closed', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_assignments', to='encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_assignments', to='patients.patient')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['bed', 'assigned_at'], name='facilities__bed_id_4ad7c4_idx'), models.Index(fields=['patient', 'assigned_at'], name='facilities__patient_25a072_idx')],
            },
        ),
    ]
