# Generated by Django 5.2.7 on 2026-01-06 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_bedassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('LAB', 'Lab Scientist'), ('PHARMACY', 'Pharmacist'), ('FRONTDESK', 'Front Desk'), ('ADMIN', 'Admin')], max_length=32)),
                ('can_manage_pharmacy_catalog', models.BooleanField(default=True, help_text='Create, edit, delete drugs in pharmacy catalog')),
                ('can_manage_pharmacy_stock', models.BooleanField(default=True, help_text='Adjust pharmacy stock levels')),
                ('can_dispense_prescriptions', models.BooleanField(default=True, help_text='Dispense medications to patients')),
                ('can_view_prescriptions', models.BooleanField(default=True, help_text='View prescription orders')),
                ('can_manage_lab_catalog', models.BooleanField(default=True, help_text='Create, edit, delete lab tests in catalog')),
                ('can_process_lab_orders', models.BooleanField(default=True, help_text='Collect samples and enter results')),
                ('can_view_lab_orders', models.BooleanField(default=True, help_text='View lab orders and results')),
                ('can_create_encounters', models.BooleanField(default=True, help_text='Start new patient encounters')),
                ('can_view_all_encounters', models.BooleanField(default=True, help_text='View all facility encounters (not just assigned ones)')),
                ('can_edit_encounters', models.BooleanField(default=True, help_text='Edit encounter details and SOAP notes')),
                ('can_close_encounters', models.BooleanField(default=True, help_text='Close and lock encounters')),
                ('can_assign_providers', models.BooleanField(default=True, help_text='Assign doctors to encounters')),
                ('can_manage_appointments', models.BooleanField(default=True, help_text='Create, edit, cancel appointments')),
                ('can_view_all_appointments', models.BooleanField(default=True, help_text='View all facility appointments')),
                ('can_check_in_appointments', models.BooleanField(default=True, help_text='Check in patients for appointments')),
                ('can_create_charges', models.BooleanField(default=True, help_text='Create billing charges')),
                ('can_view_billing', models.BooleanField(default=True, help_text='View patient billing information')),
                ('can_manage_payments', models.BooleanField(default=True, help_text='Record and manage payments')),
                ('can_create_patients', models.BooleanField(default=True, help_text='Register new patients')),
                ('can_view_all_patients', models.BooleanField(default=True, help_text='View all facility patients')),
                ('can_edit_patient_records', models.BooleanField(default=True, help_text='Edit patient information')),
                ('can_record_vitals', models.BooleanField(default=True, help_text='Record patient vital signs')),
                ('can_view_vitals', models.BooleanField(default=True, help_text='View patient vitals')),
                ('can_manage_wards', models.BooleanField(default=True, help_text='Create and manage wards and beds')),
                ('can_assign_beds', models.BooleanField(default=True, help_text='Assign patients to beds')),
                ('can_discharge_patients', models.BooleanField(default=True, help_text='Discharge patients from beds')),
                ('can_manage_hmo_pricing', models.BooleanField(default=False, help_text='Set and manage HMO-specific pricing')),
                ('can_manage_facility_settings', models.BooleanField(default=False, help_text='Edit facility information and settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='facilities.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['facility', 'role'],
                'unique_together': {('facility', 'role')},
            },
        ),
    ]
