# Generated by ChatGPT patch (manual) on 2026-01-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('modules_enabled', models.JSONField(blank=True, default=dict)),
                ('patient_seq', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_events_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('community', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='outreach.outreachevent')),
            ],
            options={
                'unique_together': {('outreach_event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OutreachPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age_years', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(130)])),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('community', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_patients_created', to=settings.AUTH_USER_MODEL)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='outreach.outreachevent')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='outreach.outreachsite')),
            ],
            options={
                'unique_together': {('outreach_event', 'patient_code')},
            },
        ),
        migrations.AddIndex(
            model_name='outreachpatient',
            index=models.Index(fields=['outreach_event', 'patient_code'], name='outreach_ou_outreach_2ea1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='outreachpatient',
            index=models.Index(fields=['outreach_event', 'full_name'], name='outreach_ou_outreach_279b30_idx'),
        ),
        migrations.AddIndex(
            model_name='outreachpatient',
            index=models.Index(fields=['outreach_event', 'phone'], name='outreach_ou_outreach_46398b_idx'),
        ),
        migrations.CreateModel(
            name='OutreachStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_template', models.CharField(blank=True, default='', max_length=40)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('all_sites', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_staff_created', to=settings.AUTH_USER_MODEL)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='outreach.outreachevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('outreach_event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='OutreachVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_sys', models.IntegerField(blank=True, null=True)),
                ('bp_dia', models.IntegerField(blank=True, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='outreach.outreachevent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='outreach.outreachpatient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_vitals_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('diagnosis_tags', models.JSONField(blank=True, default=list)),
                ('plan', models.TextField(blank=True, default='')),
                ('referral_note', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='outreach.outreachevent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='outreach.outreachpatient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_encounters_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachLabTestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=60)),
                ('ref_low', models.CharField(blank=True, default='', max_length=60)),
                ('ref_high', models.CharField(blank=True, default='', max_length=60)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_lab_tests_created', to=settings.AUTH_USER_MODEL)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='outreach.outreachevent')),
            ],
            options={
                'unique_together': {('outreach_event', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='outreachlabtestcatalog',
            index=models.Index(fields=['outreach_event', 'code'], name='outreach_ou_outreach_2515bb_idx'),
        ),
        migrations.AddIndex(
            model_name='outreachlabtestcatalog',
            index=models.Index(fields=['outreach_event', 'name'], name='outreach_ou_outreach_a4bced_idx'),
        ),
        migrations.CreateModel(
            name='OutreachLabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('COLLECTED', 'Collected'), ('RESULT_READY', 'Result Ready')], default='ORDERED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('result_ready_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_lab_orders_created', to=settings.AUTH_USER_MODEL)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='outreach.outreachevent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='outreach.outreachpatient')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachLabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outreach.outreachlaborder')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='outreach.outreachlabtestcatalog')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachLabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('result_value', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='outreach.outreachlaborderitem')),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='outreach.outreachlaborder')),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='outreach.outreachevent')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_lab_results_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachDrugCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('strength', models.CharField(blank=True, default='', max_length=120)),
                ('form', models.CharField(blank=True, default='', max_length=120)),
                ('route', models.CharField(blank=True, default='', max_length=120)),
                ('qty_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_drugs_created', to=settings.AUTH_USER_MODEL)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='outreach.outreachevent')),
            ],
            options={
                'unique_together': {('outreach_event', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='outreachdrugcatalog',
            index=models.Index(fields=['outreach_event', 'code'], name='outreach_ou_outreach_e02847_idx'),
        ),
        migrations.AddIndex(
            model_name='outreachdrugcatalog',
            index=models.Index(fields=['outreach_event', 'name'], name='outreach_ou_outreach_423139_idx'),
        ),
        migrations.CreateModel(
            name='OutreachDispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('strength', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('instruction', models.TextField(blank=True, default='')),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_dispenses_recorded', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses', to='outreach.outreachdrugcatalog')),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='outreach.outreachevent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='outreach.outreachpatient')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachImmunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255)),
                ('dose_number', models.PositiveIntegerField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, default='', max_length=120)),
                ('route', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_immunizations_recorded', to=settings.AUTH_USER_MODEL)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='outreach.outreachevent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='outreach.outreachpatient')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachBloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not eligible')], default='ELIGIBLE', max_length=20)),
                ('deferral_reason', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(choices=[('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], default='COMPLETED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donations', to='outreach.outreachevent')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_donations', to='outreach.outreachpatient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_blood_donations_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachCounseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.JSONField(blank=True, default=list)),
                ('session_notes', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility_level', models.CharField(choices=[('PRIVATE', 'Private (counselor + OSA)'), ('INTERNAL', 'Internal (staff with permission)')], default='PRIVATE', max_length=20)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_counseling_recorded', to=settings.AUTH_USER_MODEL)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='outreach.outreachevent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='outreach.outreachpatient')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachMaternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_status', models.CharField(choices=[('PREGNANT', 'Pregnant'), ('NOT_PREGNANT', 'Not pregnant'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('gestational_age_weeks', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternal_records', to='outreach.outreachevent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternal_records', to='outreach.outreachpatient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_maternal_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='outreach.outreachevent')),
            ],
            options={
                'indexes': [models.Index(fields=['outreach_event', 'created_at'], name='outreach_ou_outreach_04b174_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutreachExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(max_length=60)),
                ('export_format', models.CharField(default='csv', max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='outreach/exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_exports_created', to=settings.AUTH_USER_MODEL)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='outreach.outreachevent')),
            ],
        ),
        migrations.AddField(
            model_name='outreachstaffprofile',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='staff', to='outreach.outreachsite'),
        ),
    ]
