# Generated by Django 5.2.7 on 2026-01-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outreachauditlog',
            new_name='outreach_ou_outreac_5da681_idx',
            old_name='outreach_ou_outreach_04b174_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachdrugcatalog',
            new_name='outreach_ou_outreac_652c09_idx',
            old_name='outreach_ou_outreach_e02847_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachdrugcatalog',
            new_name='outreach_ou_outreac_71a67d_idx',
            old_name='outreach_ou_outreach_423139_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachlabtestcatalog',
            new_name='outreach_ou_outreac_76b064_idx',
            old_name='outreach_ou_outreach_2515bb_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachlabtestcatalog',
            new_name='outreach_ou_outreac_2b8738_idx',
            old_name='outreach_ou_outreach_a4bced_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachpatient',
            new_name='outreach_ou_outreac_0fe0cf_idx',
            old_name='outreach_ou_outreach_2ea1f4_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachpatient',
            new_name='outreach_ou_outreac_6bd367_idx',
            old_name='outreach_ou_outreach_279b30_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachpatient',
            new_name='outreach_ou_outreac_6141e7_idx',
            old_name='outreach_ou_outreach_46398b_idx',
        ),
    ]
