# Generated by Django 5.2.7 on 2026-01-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_rename_outreach_ou_outreach_04b174_idx_outreach_ou_outreac_5da681_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachencounter',
            name='soap_note_attachment',
            field=models.FileField(blank=True, null=True, upload_to='outreach/encounters/soap_notes/'),
        ),
        migrations.AddField(
            model_name='outreachlabresult',
            name='result_attachment',
            field=models.FileField(blank=True, null=True, upload_to='outreach/labs/results/'),
        ),
    ]
