# Generated by Django 5.2.7 on 2026-01-30 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_outreachencounter_soap_note_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachVaccineCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=80)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_vaccines_created', to=settings.AUTH_USER_MODEL)),
                ('outreach_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='outreach.outreachevent')),
            ],
            options={
                'indexes': [models.Index(fields=['outreach_event', 'name'], name='outreach_ou_outreac_fb2379_idx')],
                'unique_together': {('outreach_event', 'name')},
            },
        ),
    ]
