# Generated by Django 5.2.7 on 2026-02-02 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0005_outreachlabresult_result_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachDentalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachEyeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachSurgical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='outreachblooddonation',
            name='blood_group',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='outreachblooddonation',
            name='genotype',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('SC', 'SC'), ('CC', 'CC')], default='UNKNOWN', max_length=8),
        ),
        migrations.AddField(
            model_name='outreachpatient',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='outreachstaffprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='outreachstaffprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='outreachpatient',
            index=models.Index(fields=['outreach_event', 'email'], name='outreach_patient_evt_email_idx'),
        ),
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='outreach_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_checks', to='outreach.outreachevent'),
        ),
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_checks', to='outreach.outreachpatient'),
        ),
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_dental_checks_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='outreach_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_checks', to='outreach.outreachevent'),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_checks', to='outreach.outreachpatient'),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_eye_checks_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outreachreferral',
            name='outreach_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='outreach.outreachevent'),
        ),
        migrations.AddField(
            model_name='outreachreferral',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='outreach.outreachpatient'),
        ),
        migrations.AddField(
            model_name='outreachreferral',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_referrals_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outreachsurgical',
            name='outreach_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgicals', to='outreach.outreachevent'),
        ),
        migrations.AddField(
            model_name='outreachsurgical',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgicals', to='outreach.outreachpatient'),
        ),
        migrations.AddField(
            model_name='outreachsurgical',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_surgicals_recorded', to=settings.AUTH_USER_MODEL),
        ),
    ]
