# Generated by Django 5.2.7 on 2026-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0006_outreachdentalcheck_outreacheyecheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='chief_complaint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='diagnosis_assessment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='oral_examination_findings',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='procedure_done',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('NEEDS_FOLLOW_UP', 'Needs follow-up'), ('REFERRED', 'Referred')], default='COMPLETED', max_length=30),
        ),
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='tooth_area_involved',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='outreachdentalcheck',
            name='visit_type',
            field=models.CharField(choices=[('SCREENING', 'Screening'), ('COMPLAINT_BASED', 'Complaint-based'), ('FOLLOW_UP', 'Follow-up')], default='SCREENING', max_length=30),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='assessment_diagnosis',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='chief_complaint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='eye_exam_findings',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('NEEDS_FOLLOW_UP', 'Needs follow-up'), ('REFERRED', 'Referred')], default='COMPLETED', max_length=30),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='visit_type',
            field=models.CharField(choices=[('SCREENING', 'Screening'), ('COMPLAINT_BASED', 'Complaint-based'), ('FOLLOW_UP', 'Follow-up')], default='SCREENING', max_length=30),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='visual_acuity_left',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='outreacheyecheck',
            name='visual_acuity_right',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='outreachreferral',
            name='reason_for_referral',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreachreferral',
            name='referral_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='outreachreferral',
            name='referred_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='outreachsurgical',
            name='consent_obtained',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not applicable')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='outreachsurgical',
            name='indication',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreachsurgical',
            name='procedure_category',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='outreachsurgical',
            name='procedure_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='outreachsurgical',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('ABORTED', 'Aborted'), ('REFERRED', 'Referred')], default='PLANNED', max_length=20),
        ),
    ]
