# Generated by Django 5.2.7 on 2025-12-17 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_bedassignment'),
        ('patients', '0005_alter_patientdocument_options_and_more'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='outsourced_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='drug_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pharmacy.drug'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['outsourced_to', 'created_at'], name='pharmacy_pr_outsour_adb5d7_idx'),
        ),
    ]
