# Generated by Django 5.2.7 on 2025-12-19 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_bedassignment'),
        ('pharmacy', '0002_prescription_outsourced_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Creator (used for independent pharmacy scoping when facility is null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drug',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility this drug belongs to (null for independent pharmacies)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['facility', 'is_active'], name='pharmacy_dr_facilit_f9f5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['created_by', 'is_active'], name='pharmacy_dr_created_36d3a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='drug',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False)), fields=('code', 'facility'), name='unique_drug_code_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='drug',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False), ('facility__isnull', True)), fields=('code', 'created_by'), name='unique_drug_code_per_user'),
        ),
    ]
