# Generated by Django 5.2.7 on 2025-12-23 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_bedassignment'),
        ('pharmacy', '0003_drug_created_by_drug_facility_alter_drug_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Independent pharmacy owner (used when facility is null)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_stock_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Independent pharmacy owner (used when facility is null)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_stock_txns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='stocktxn',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_txns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocktxn',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False)), fields=('facility', 'drug'), name='unique_stock_per_facility_drug'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'drug'), name='unique_stock_per_owner_drug'),
        ),
    ]
