# Generated by Django 5.2.7 on 2025-12-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_stockitem_unique_together_stockitem_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='max_stock_level',
            field=models.PositiveIntegerField(default=0, help_text='Maximum stock level ever recorded (used for auto-calculating reorder level)'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0, help_text='Minimum stock level before reorder alert (0 means auto-calculate at 20% of max historical stock)'),
        ),
    ]
