# Generated by Django 5.2.7 on 2025-12-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by_facility',
            field=models.BooleanField(default=False),
        ),
    ]
