# Generated by Django 5.2.7 on 2026-01-08 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_created_by_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sacked',
            field=models.BooleanField(default=False, help_text='Provider has been sacked/terminated from their facility'),
        ),
        migrations.AddField(
            model_name='user',
            name='sacked_at',
            field=models.DateTimeField(blank=True, help_text='When the provider was sacked', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sacked_by',
            field=models.ForeignKey(blank=True, help_text='Admin who sacked this provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers_sacked', to=settings.AUTH_USER_MODEL),
        ),
    ]
