# Generated by Django 5.2.7 on 2025-10-15 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('ENCOUNTER', 'Encounter Summary'), ('LAB', 'Lab Result'), ('IMAGING', 'Imaging Report'), ('BILLING', 'Billing Statement')], max_length=16)),
                ('ref_id', models.PositiveIntegerField()),
                ('format', models.CharField(default='PDF', max_length=8)),
                ('saved_as_attachment_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
