# Generated by Django 5.2.7 on 2025-10-15 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_type', models.CharField(choices=[('CONSULT', 'Consultation'), ('FOLLOW_UP', 'Follow-up'), ('LAB', 'Lab Visit'), ('IMAGING', 'Imaging Visit'), ('PHARMACY', 'Pharmacy Pickup'), ('OTHER', 'Other')], default='CONSULT', max_length=16)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked-in'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show')], default='SCHEDULED', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('encounter_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lab_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('imaging_request_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_provided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at', 'id'],
                'indexes': [models.Index(fields=['facility', 'start_at'], name='appointment_facilit_2dbabf_idx'), models.Index(fields=['provider', 'start_at'], name='appointment_provide_486882_idx'), models.Index(fields=['patient', 'start_at'], name='appointment_patient_4b5ed5_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
            },
        ),
    ]
