# Generated by Django 5.2.7 on 2026-01-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appt_type',
            field=models.CharField(choices=[('CONSULT', 'Consultation'), ('FOLLOW_UP', 'Follow-up'), ('PROCEDURE', 'Procedure'), ('DIAGNOSTIC', 'Diagnostic (Non-Lab)'), ('NURSING_CARE', 'Nursing Care'), ('THERAPY', 'Therapy / Rehab'), ('MENTAL_HEALTH', 'Mental Health'), ('IMMUNIZATION', 'Immunization'), ('MATERNAL_CHILD', 'Maternal / Child Care'), ('SURGICAL', 'Surgical (Pre / Post)'), ('EMERGENCY', 'Emergency (Non-ER)'), ('TELEMEDICINE', 'Telemedicine'), ('HOME_VISIT', 'Home Visit'), ('ADMIN_HMO', 'Administrative / HMO Review'), ('LAB', 'Lab Visit'), ('IMAGING', 'Imaging Visit'), ('PHARMACY', 'Pharmacy Pickup'), ('OTHER', 'Other')], default='CONSULT', max_length=16),
        ),
    ]
