# Generated by Django 5.2.7 on 2025-10-15 10:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(help_text='When vitals were taken')),
                ('systolic', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('diastolic', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)])),
                ('temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resp_rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(80)])),
                ('spo2', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp_flag', models.CharField(blank=True, choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=8, null=True)),
                ('temp_flag', models.CharField(blank=True, choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=8, null=True)),
                ('spo2_flag', models.CharField(blank=True, choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=8, null=True)),
                ('overall', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='GREEN', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_at', '-id'],
                'indexes': [models.Index(fields=['patient', 'measured_at'], name='vitals_vita_patient_12f2db_idx'), models.Index(fields=['facility', 'measured_at'], name='vitals_vita_facilit_3988ee_idx')],
            },
        ),
    ]
