# Generated by Django 5.2.7 on 2025-10-15 14:30

import attachments.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=attachments.models.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'tif', 'tiff', 'bmp', 'gif'])])),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private (staff only, facility-scoped)'), ('PATIENT', 'Visible to the patient (and staff)'), ('INTERNAL', 'Internal (admins only)')], default='PRIVATE', max_length=16)),
                ('tag', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='facilities.facility')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='attachments.file')),
            ],
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['facility', 'patient', 'created_at'], name='attachments_facilit_e6204c_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['visibility'], name='attachments_visibil_011d48_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['sha256'], name='attachments_sha256_061f8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attachmentlink',
            unique_together={('file', 'content_type', 'object_id')},
        ),
    ]
