# Generated by Django 5.2.7 on 2025-10-15 09:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(blank=True, max_length=120)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must be E.164 format (e.g. +2348012345678).', regex='^\\+\\d{1,3}\\d{6,14}$')])),
                ('country', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('lga', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('insurance_status', models.CharField(choices=[('SELF_PAY', 'Self pay'), ('INSURED', 'Insured')], default='SELF_PAY', max_length=16)),
                ('hmo_plan', models.CharField(blank=True, max_length=120)),
                ('blood_group', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('OTHER', 'Other')], max_length=8)),
                ('blood_group_other', models.CharField(blank=True, max_length=3)),
                ('genotype', models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SC', 'SC'), ('AC', 'AC'), ('OTHER', 'Other')], max_length=8)),
                ('genotype_other', models.CharField(blank=True, max_length=2)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('patient_status', models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('INPATIENT', 'Inpatient'), ('DISCHARGED', 'Discharged')], default='OUTPATIENT', max_length=16)),
                ('default_encounter_type', models.CharField(choices=[('NEW', 'New'), ('FOLLOW_UP', 'Follow-up'), ('VIRTUAL', 'Virtual')], default='NEW', max_length=16)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must be E.164 format (e.g. +2348012345678).', regex='^\\+\\d{1,3}\\d{6,14}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='facilities.facility')),
                ('guardian_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to=settings.AUTH_USER_MODEL)),
                ('hmo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.hmo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(upload_to='patient_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
