# Generated by Django 5.2.7 on 2025-10-27 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='parent_patient',
            field=models.ForeignKey(blank=True, help_text='If set, this Patient is a dependent of `parent_patient`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='guardian_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_dependents', to=settings.AUTH_USER_MODEL),
        ),
    ]
