# Generated by Django 5.2.7 on 2025-11-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='relationship_to_guardian',
            field=models.CharField(blank=True, help_text='Relationship of this dependent to their parent/guardian, e.g. Son, Daughter, Spouse.', max_length=64),
        ),
    ]
