# Generated by Django 5.2.7 on 2025-12-09 09:46

import django.db.models.deletion
import patients.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_relationship_to_guardian'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdocument',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='patientdocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='uploaded_by_user',
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='document_type',
            field=models.CharField(choices=[('BLOOD_TEST', 'Blood test'), ('XRAY', 'X-ray'), ('ULTRASOUND', 'Ultrasound'), ('DISCHARGE_SUMMARY', 'Discharge summary'), ('REFERRAL_NOTE', 'Referral note'), ('LAB_RESULT', 'Lab result'), ('CT_SCAN', 'CT scan'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='uploaded_by_role',
            field=models.CharField(choices=[('PATIENT', 'Uploaded by patient'), ('DOCTOR', 'Uploaded by doctor'), ('NURSE', 'Uploaded by nurse'), ('ADMIN', 'Uploaded by admin'), ('SYSTEM', 'System')], default='PATIENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='file',
            field=models.FileField(upload_to=patients.models.patient_document_upload_path),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
