# Generated by Django 5.2.7 on 2025-12-19 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patientdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.CharField(help_text='The substance the patient is allergic to (e.g., Penicillin, Peanuts)', max_length=255)),
                ('allergy_type', models.CharField(choices=[('DRUG', 'Drug / Medication'), ('FOOD', 'Food'), ('ENVIRONMENTAL', 'Environmental'), ('INSECT', 'Insect'), ('LATEX', 'Latex'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('LIFE_THREATENING', 'Life-threatening')], default='MODERATE', max_length=20)),
                ('reaction', models.TextField(blank=True, help_text='Description of the allergic reaction (e.g., rash, anaphylaxis)')),
                ('onset_date', models.DateField(blank=True, help_text='When the allergy was first identified or occurred', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Allergies',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'allergen'), name='unique_patient_allergen')],
            },
        ),
    ]
