# Generated by Django 5.2.7 on 2026-01-03 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_bedassignment'),
        ('patients', '0007_patientproviderlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hmo',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='hmo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hmo',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hmos', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='hmo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hmo',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='hmo',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='uniq_hmo_name_per_facility'),
        ),
    ]
