# Generated by Django 5.2.7 on 2026-01-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_hmo_options_hmo_created_at_hmo_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_expiry',
            field=models.DateField(blank=True, help_text='Insurance coverage expiry date', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_notes',
            field=models.TextField(blank=True, help_text='Additional insurance information'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, help_text='Insurance card number or policy ID', max_length=120),
        ),
    ]
