# Generated by Django 5.2.7 on 2026-01-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_insurance_expiry_patient_insurance_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmo',
            name='addresses',
            field=models.JSONField(blank=True, default=list, help_text='List of HMO office addresses'),
        ),
        migrations.AddField(
            model_name='hmo',
            name='contact_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of contact phone numbers'),
        ),
        migrations.AddField(
            model_name='hmo',
            name='contact_person_email',
            field=models.EmailField(blank=True, help_text='Contact person email address', max_length=254),
        ),
        migrations.AddField(
            model_name='hmo',
            name='contact_person_name',
            field=models.CharField(blank=True, help_text='Name of HMO contact person', max_length=255),
        ),
        migrations.AddField(
            model_name='hmo',
            name='contact_person_phone',
            field=models.CharField(blank=True, help_text='Contact person phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='hmo',
            name='email',
            field=models.EmailField(blank=True, help_text='HMO primary email address', max_length=254),
        ),
        migrations.AddField(
            model_name='hmo',
            name='nhis_number',
            field=models.CharField(blank=True, default='', help_text='NHIS registration number', max_length=120),
        ),
        migrations.AddField(
            model_name='hmo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
