# Generated by Django 5.2.7 on 2026-01-08 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_hmo_addresses_hmo_contact_numbers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hmo',
            name='relationship_notes',
            field=models.TextField(blank=True, help_text='Notes about the relationship status'),
        ),
        migrations.AddField(
            model_name='hmo',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('BAD', 'Bad')], default='GOOD', help_text='Current relationship status with this HMO', max_length=20),
        ),
        migrations.AddField(
            model_name='hmo',
            name='relationship_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the relationship status was last updated', null=True),
        ),
        migrations.AddField(
            model_name='hmo',
            name='relationship_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hmo_relationship_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
