# Generated by Django 5.2.7 on 2026-01-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_facility_is_publicly_visible'),
        ('patients', '0011_hmo_relationship_notes_hmo_relationship_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HMOTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tier name (Gold, Silver, Bronze)', max_length=64)),
                ('level', models.PositiveIntegerField(help_text='Tier level for ordering (1=Gold/highest, 2=Silver, 3=Bronze/lowest)')),
                ('description', models.TextField(blank=True, help_text='Description of tier benefits and coverage')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tier is available for patient enrollment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HMO Tier',
                'verbose_name_plural': 'HMO Tiers',
                'ordering': ['system_hmo', 'level'],
            },
        ),
        migrations.CreateModel(
            name='SystemHMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Official HMO name (e.g., 'Leadway Health', 'NHIS')", max_length=255, unique=True)),
                ('nhis_number', models.CharField(blank=True, default='', help_text='NHIS registration number', max_length=120)),
                ('email', models.EmailField(blank=True, help_text='HMO primary email address', max_length=254)),
                ('addresses', models.JSONField(blank=True, default=list, help_text='List of HMO office addresses')),
                ('contact_numbers', models.JSONField(blank=True, default=list, help_text='List of contact phone numbers')),
                ('contact_person_name', models.CharField(blank=True, help_text='Name of HMO contact person', max_length=255)),
                ('contact_person_phone', models.CharField(blank=True, help_text='Contact person phone number', max_length=20)),
                ('contact_person_email', models.EmailField(blank=True, help_text='Contact person email address', max_length=254)),
                ('website', models.URLField(blank=True, help_text='HMO website URL', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional information about this HMO')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this HMO is available for facility enrollment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System HMO',
                'verbose_name_plural': 'System HMOs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='hmo_enrolled_at',
            field=models.DateTimeField(blank=True, help_text='When patient enrolled with current HMO', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hmo_enrollment_facility',
            field=models.ForeignKey(blank=True, help_text='Facility where patient first enrolled with current HMO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hmo_enrolled_patients', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hmo_enrollment_provider',
            field=models.ForeignKey(blank=True, help_text='Independent provider where patient first enrolled with current HMO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hmo_enrolled_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='hmo_tier',
            field=models.ForeignKey(blank=True, help_text='The tier level of HMO coverage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.hmotier'),
        ),
        migrations.AddField(
            model_name='hmotier',
            name='system_hmo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='patients.systemhmo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='system_hmo',
            field=models.ForeignKey(blank=True, help_text='System-level HMO the patient is enrolled with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.systemhmo'),
        ),
        migrations.CreateModel(
            name='PatientFacilityHMOApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_number', models.CharField(blank=True, help_text='Insurance card number', max_length=120)),
                ('insurance_expiry', models.DateField(blank=True, help_text='Insurance expiry date', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('request_notes', models.TextField(blank=True, help_text='Notes from the patient or referring facility')),
                ('decision_notes', models.TextField(blank=True, help_text='Notes from the approving facility/provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hmo_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_hmo_approvals', to='facilities.facility')),
                ('original_facility', models.ForeignKey(blank=True, help_text='Facility where patient originally enrolled with this HMO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='facilities.facility')),
                ('original_provider', models.ForeignKey(blank=True, help_text='Independent provider where patient originally enrolled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Independent provider reviewing the approval', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_patient_hmo_approvals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmo_facility_approvals', to='patients.patient')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_approvals', to='patients.hmotier')),
                ('system_hmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_approvals', to='patients.systemhmo')),
            ],
            options={
                'verbose_name': 'Patient Facility HMO Approval',
                'verbose_name_plural': 'Patient Facility HMO Approvals',
                'ordering': ['-requested_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('facility__isnull', False), ('owner__isnull', True)), models.Q(('facility__isnull', True), ('owner__isnull', False)), _connector='OR'), name='patient_hmo_approval_scope_xor'), models.UniqueConstraint(condition=models.Q(('facility__isnull', False), ('status', 'PENDING')), fields=('patient', 'facility'), name='unique_pending_patient_facility_hmo_approval'), models.UniqueConstraint(condition=models.Q(('owner__isnull', False), ('status', 'PENDING')), fields=('patient', 'owner'), name='unique_pending_patient_owner_hmo_approval')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='hmotier',
            unique_together={('system_hmo', 'level')},
        ),
        migrations.CreateModel(
            name='FacilityHMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_status', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('BAD', 'Bad')], default='GOOD', help_text='Current relationship status with this HMO', max_length=20)),
                ('relationship_notes', models.TextField(blank=True, help_text='Notes about the relationship (payment history, issues, etc.)')),
                ('relationship_updated_at', models.DateTimeField(blank=True, help_text='When the relationship status was last updated', null=True)),
                ('contract_start_date', models.DateField(blank=True, help_text='Start date of contract with this HMO', null=True)),
                ('contract_end_date', models.DateField(blank=True, help_text='End date of contract with this HMO', null=True)),
                ('contract_reference', models.CharField(blank=True, help_text='Contract reference number', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this facility currently works with this HMO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, help_text='Facility that enabled this HMO', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_hmos', to='facilities.facility')),
                ('owner', models.ForeignKey(blank=True, help_text='Independent provider who enabled this HMO', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_hmos', to=settings.AUTH_USER_MODEL)),
                ('relationship_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_hmo_relationship_updates', to=settings.AUTH_USER_MODEL)),
                ('system_hmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_links', to='patients.systemhmo')),
            ],
            options={
                'verbose_name': 'Facility HMO',
                'verbose_name_plural': 'Facility HMOs',
                'ordering': ['system_hmo__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('facility__isnull', False), ('owner__isnull', True)), models.Q(('facility__isnull', True), ('owner__isnull', False)), _connector='OR'), name='facility_hmo_scope_xor'), models.UniqueConstraint(condition=models.Q(('facility__isnull', False)), fields=('facility', 'system_hmo'), name='unique_facility_system_hmo'), models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'system_hmo'), name='unique_owner_system_hmo')],
            },
        ),
    ]
