# Generated by Django 5.2.7 on 2026-01-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_hmotier_systemhmo_patient_hmo_enrolled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityhmo',
            name='addresses',
            field=models.JSONField(blank=True, default=list, help_text='Facility-specific HMO office addresses (JSON array)'),
        ),
        migrations.AddField(
            model_name='facilityhmo',
            name='contact_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Facility-specific contact phone numbers (JSON array)'),
        ),
        migrations.AddField(
            model_name='facilityhmo',
            name='contact_person_email',
            field=models.EmailField(blank=True, default='', help_text='Facility-specific contact person email address', max_length=254),
        ),
        migrations.AddField(
            model_name='facilityhmo',
            name='contact_person_name',
            field=models.CharField(blank=True, default='', help_text='Name of facility-specific HMO contact person', max_length=255),
        ),
        migrations.AddField(
            model_name='facilityhmo',
            name='contact_person_phone',
            field=models.CharField(blank=True, default='', help_text='Facility-specific contact person phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='facilityhmo',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Facility-specific HMO email address', max_length=254),
        ),
        migrations.AddField(
            model_name='facilityhmo',
            name='nhis_number',
            field=models.CharField(blank=True, default='', help_text='Facility-specific NHIS number (if different from system HMO)', max_length=120),
        ),
    ]
