# Generated by Django 5.2.7 on 2026-02-07 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_facility_is_publicly_visible'),
        ('patients', '0013_facilityhmo_addresses_facilityhmo_contact_numbers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFacilityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_links', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['facility', 'patient'], name='patients_pa_facilit_68d569_idx'), models.Index(fields=['patient', 'facility'], name='patients_pa_patient_74b886_idx')],
                'unique_together': {('patient', 'facility')},
            },
        ),
    ]
