# Generated by Django 5.2.7 on 2025-10-15 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('LAB_RESULT_READY', 'Lab result ready'), ('IMAGING_REPORT_READY', 'Imaging report ready'), ('APPT_REMINDER', 'Appointment reminder'), ('BILL_CHARGE_ADDED', 'New charge added'), ('BILL_PAYMENT_POSTED', 'Payment posted'), ('GENERAL', 'General')], default='GENERAL', max_length=40)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'), models.Index(fields=['facility', 'created_at'], name='notificatio_facilit_cd1849_idx'), models.Index(fields=['topic'], name='notificatio_topic_9c29fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('LAB_RESULT_READY', 'Lab result ready'), ('IMAGING_REPORT_READY', 'Imaging report ready'), ('APPT_REMINDER', 'Appointment reminder'), ('BILL_CHARGE_ADDED', 'New charge added'), ('BILL_PAYMENT_POSTED', 'Payment posted'), ('GENERAL', 'General')], max_length=40)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email')], default='IN_APP', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic', 'channel')},
            },
        ),
    ]
