# Generated by Django 5.2.7 on 2025-12-09 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('patients', '0005_alter_patientdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('VITALS', 'Vitals'), ('MEDICATION', 'Medication'), ('LAB', 'Lab Test'), ('APPOINTMENT', 'Appointment'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('message', models.TextField()),
                ('reminder_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='patients.patient')),
            ],
            options={
                'ordering': ['reminder_time'],
            },
        ),
    ]
