# Generated by Django 5.2.7 on 2025-12-22 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_bedassignment'),
        ('notifications', '0002_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('LAB_RESULT_READY', 'Lab result ready'), ('LAB_RESULT_CRITICAL', 'Critical lab result'), ('IMAGING_REPORT_READY', 'Imaging report ready'), ('PRESCRIPTION_READY', 'Prescription ready'), ('PRESCRIPTION_REFILL', 'Prescription refill reminder'), ('APPT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_CONFIRMED', 'Appointment confirmed'), ('APPOINTMENT_CHECKED_IN', 'Appointment checked-in'), ('APPOINTMENT_COMPLETED', 'Appointment completed'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('APPOINTMENT_NO_SHOW', 'Appointment no-show'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('ENCOUNTER_CREATED', 'Encounter created'), ('ENCOUNTER_UPDATED', 'Encounter updated'), ('ENCOUNTER_COMPLETED', 'Encounter completed'), ('BILL_CHARGE_ADDED', 'New charge added'), ('BILL_PAYMENT_POSTED', 'Payment posted'), ('BILLING', 'Billing'), ('PAYMENT_DUE', 'Payment due'), ('PAYMENT_RECEIVED', 'Payment received'), ('STAFF_ASSIGNED', 'Staff assigned'), ('MESSAGE', 'Message'), ('REMINDER', 'Reminder'), ('VITAL_ALERT', 'Vital alert'), ('ALLERGY_ALERT', 'Allergy alert'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('SYSTEM_MAINTENANCE', 'System maintenance'), ('ACCOUNT', 'Account'), ('GENERAL', 'General')], default='SYSTEM_ANNOUNCEMENT', max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, default='', max_length=240)),
                ('audience_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='notification',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='group_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.CharField(choices=[('LAB_RESULT_READY', 'Lab result ready'), ('LAB_RESULT_CRITICAL', 'Critical lab result'), ('IMAGING_REPORT_READY', 'Imaging report ready'), ('PRESCRIPTION_READY', 'Prescription ready'), ('PRESCRIPTION_REFILL', 'Prescription refill reminder'), ('APPT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_CONFIRMED', 'Appointment confirmed'), ('APPOINTMENT_CHECKED_IN', 'Appointment checked-in'), ('APPOINTMENT_COMPLETED', 'Appointment completed'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('APPOINTMENT_NO_SHOW', 'Appointment no-show'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('ENCOUNTER_CREATED', 'Encounter created'), ('ENCOUNTER_UPDATED', 'Encounter updated'), ('ENCOUNTER_COMPLETED', 'Encounter completed'), ('BILL_CHARGE_ADDED', 'New charge added'), ('BILL_PAYMENT_POSTED', 'Payment posted'), ('BILLING', 'Billing'), ('PAYMENT_DUE', 'Payment due'), ('PAYMENT_RECEIVED', 'Payment received'), ('STAFF_ASSIGNED', 'Staff assigned'), ('MESSAGE', 'Message'), ('REMINDER', 'Reminder'), ('VITAL_ALERT', 'Vital alert'), ('ALLERGY_ALERT', 'Allergy alert'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('SYSTEM_MAINTENANCE', 'System maintenance'), ('ACCOUNT', 'Account'), ('GENERAL', 'General')], default='GENERAL', max_length=40),
        ),
        migrations.AlterField(
            model_name='preference',
            name='topic',
            field=models.CharField(choices=[('LAB_RESULT_READY', 'Lab result ready'), ('LAB_RESULT_CRITICAL', 'Critical lab result'), ('IMAGING_REPORT_READY', 'Imaging report ready'), ('PRESCRIPTION_READY', 'Prescription ready'), ('PRESCRIPTION_REFILL', 'Prescription refill reminder'), ('APPT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_CONFIRMED', 'Appointment confirmed'), ('APPOINTMENT_CHECKED_IN', 'Appointment checked-in'), ('APPOINTMENT_COMPLETED', 'Appointment completed'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('APPOINTMENT_NO_SHOW', 'Appointment no-show'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('ENCOUNTER_CREATED', 'Encounter created'), ('ENCOUNTER_UPDATED', 'Encounter updated'), ('ENCOUNTER_COMPLETED', 'Encounter completed'), ('BILL_CHARGE_ADDED', 'New charge added'), ('BILL_PAYMENT_POSTED', 'Payment posted'), ('BILLING', 'Billing'), ('PAYMENT_DUE', 'Payment due'), ('PAYMENT_RECEIVED', 'Payment received'), ('STAFF_ASSIGNED', 'Staff assigned'), ('MESSAGE', 'Message'), ('REMINDER', 'Reminder'), ('VITAL_ALERT', 'Vital alert'), ('ALLERGY_ALERT', 'Allergy alert'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('SYSTEM_MAINTENANCE', 'System maintenance'), ('ACCOUNT', 'Account'), ('GENERAL', 'General')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'archived', 'is_read', 'created_at'], name='notificatio_user_id_3003ef_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['group_key'], name='notificatio_group_k_49f5bb_idx'),
        ),
        migrations.AddField(
            model_name='facilityannouncement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityannouncement',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='facilities.facility'),
        ),
        migrations.AddIndex(
            model_name='facilityannouncement',
            index=models.Index(fields=['facility', 'is_active', 'created_at'], name='ann_fac_active_created'),
        ),
    ]
