# Generated by Django 5.2.7 on 2025-12-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_facilityannouncement_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityannouncement',
            name='topic',
            field=models.CharField(choices=[('LAB_RESULT_READY', 'Lab result ready'), ('LAB_RESULT_CRITICAL', 'Critical lab result'), ('IMAGING_REPORT_READY', 'Imaging report ready'), ('PRESCRIPTION_READY', 'Prescription ready'), ('PRESCRIPTION_REFILL', 'Prescription refill reminder'), ('APPT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_CONFIRMED', 'Appointment confirmed'), ('APPOINTMENT_CHECKED_IN', 'Appointment checked-in'), ('APPOINTMENT_COMPLETED', 'Appointment completed'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('APPOINTMENT_NO_SHOW', 'Appointment no-show'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('ENCOUNTER_CREATED', 'Encounter created'), ('ENCOUNTER_UPDATED', 'Encounter updated'), ('ENCOUNTER_COMPLETED', 'Encounter completed'), ('BILL_CHARGE_ADDED', 'New charge added'), ('BILL_PAYMENT_POSTED', 'Payment posted'), ('BILLING', 'Billing'), ('PAYMENT_DUE', 'Payment due'), ('PAYMENT_RECEIVED', 'Payment received'), ('STAFF_ASSIGNED', 'Staff assigned'), ('WARD_ADMISSION_REQUEST', 'Ward admission request'), ('MESSAGE', 'Message'), ('REMINDER', 'Reminder'), ('VITAL_ALERT', 'Vital alert'), ('ALLERGY_ALERT', 'Allergy alert'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('SYSTEM_MAINTENANCE', 'System maintenance'), ('ACCOUNT', 'Account'), ('GENERAL', 'General')], default='SYSTEM_ANNOUNCEMENT', max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.CharField(choices=[('LAB_RESULT_READY', 'Lab result ready'), ('LAB_RESULT_CRITICAL', 'Critical lab result'), ('IMAGING_REPORT_READY', 'Imaging report ready'), ('PRESCRIPTION_READY', 'Prescription ready'), ('PRESCRIPTION_REFILL', 'Prescription refill reminder'), ('APPT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_CONFIRMED', 'Appointment confirmed'), ('APPOINTMENT_CHECKED_IN', 'Appointment checked-in'), ('APPOINTMENT_COMPLETED', 'Appointment completed'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('APPOINTMENT_NO_SHOW', 'Appointment no-show'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('ENCOUNTER_CREATED', 'Encounter created'), ('ENCOUNTER_UPDATED', 'Encounter updated'), ('ENCOUNTER_COMPLETED', 'Encounter completed'), ('BILL_CHARGE_ADDED', 'New charge added'), ('BILL_PAYMENT_POSTED', 'Payment posted'), ('BILLING', 'Billing'), ('PAYMENT_DUE', 'Payment due'), ('PAYMENT_RECEIVED', 'Payment received'), ('STAFF_ASSIGNED', 'Staff assigned'), ('WARD_ADMISSION_REQUEST', 'Ward admission request'), ('MESSAGE', 'Message'), ('REMINDER', 'Reminder'), ('VITAL_ALERT', 'Vital alert'), ('ALLERGY_ALERT', 'Allergy alert'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('SYSTEM_MAINTENANCE', 'System maintenance'), ('ACCOUNT', 'Account'), ('GENERAL', 'General')], default='GENERAL', max_length=40),
        ),
        migrations.AlterField(
            model_name='preference',
            name='topic',
            field=models.CharField(choices=[('LAB_RESULT_READY', 'Lab result ready'), ('LAB_RESULT_CRITICAL', 'Critical lab result'), ('IMAGING_REPORT_READY', 'Imaging report ready'), ('PRESCRIPTION_READY', 'Prescription ready'), ('PRESCRIPTION_REFILL', 'Prescription refill reminder'), ('APPT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_REMINDER', 'Appointment reminder'), ('APPOINTMENT_CONFIRMED', 'Appointment confirmed'), ('APPOINTMENT_CHECKED_IN', 'Appointment checked-in'), ('APPOINTMENT_COMPLETED', 'Appointment completed'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('APPOINTMENT_NO_SHOW', 'Appointment no-show'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('ENCOUNTER_CREATED', 'Encounter created'), ('ENCOUNTER_UPDATED', 'Encounter updated'), ('ENCOUNTER_COMPLETED', 'Encounter completed'), ('BILL_CHARGE_ADDED', 'New charge added'), ('BILL_PAYMENT_POSTED', 'Payment posted'), ('BILLING', 'Billing'), ('PAYMENT_DUE', 'Payment due'), ('PAYMENT_RECEIVED', 'Payment received'), ('STAFF_ASSIGNED', 'Staff assigned'), ('WARD_ADMISSION_REQUEST', 'Ward admission request'), ('MESSAGE', 'Message'), ('REMINDER', 'Reminder'), ('VITAL_ALERT', 'Vital alert'), ('ALLERGY_ALERT', 'Allergy alert'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('SYSTEM_MAINTENANCE', 'System maintenance'), ('ACCOUNT', 'Account'), ('GENERAL', 'General')], max_length=40),
        ),
    ]
