# Generated by Django 5.2.7 on 2025-10-15 10:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('ref_low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ref_high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'Stat')], default='ROUTINE', max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('encounter_id', models.PositiveIntegerField(blank=True, null=True)),
                ('external_lab_name', models.CharField(blank=True, max_length=160)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='facilities.facility')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
            ],
            options={
                'ordering': ['-ordered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('result_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('result_text', models.TextField(blank=True)),
                ('result_unit', models.CharField(blank=True, max_length=40)),
                ('ref_low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ref_high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('flag', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('LOW', 'Low'), ('HIGH', 'High'), ('CRIT', 'Critical')], max_length=6)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_completed', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labs.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.labtest')),
            ],
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'ordered_at'], name='labs_labord_patient_2e307b_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['facility', 'ordered_at'], name='labs_labord_facilit_3246d9_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status'], name='labs_labord_status_745bf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='laborderitem',
            unique_together={('order', 'test')},
        ),
    ]
