# Generated by Django 5.2.7 on 2025-12-17 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_bedassignment'),
        ('labs', '0001_initial'),
        ('patients', '0005_alter_patientdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laborderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='laborder',
            name='outsourced_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='requested_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='laborderitem',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='labs.labtest'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['outsourced_to', 'ordered_at'], name='labs_labord_outsour_d05ff2_idx'),
        ),
        migrations.AddConstraint(
            model_name='laborderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('test__isnull', False)), fields=('order', 'test'), name='uniq_laborderitem_order_test_when_test_present'),
        ),
    ]
