# Generated by Django 5.2.7 on 2025-12-19 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_bedassignment'),
        ('labs', '0002_alter_laborderitem_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Creator (used for independent lab scoping when facility is null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtest',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility this test belongs to (null for independent labs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='code',
            field=models.CharField(max_length=40),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['facility', 'is_active'], name='labs_labtes_facilit_e9ee70_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['created_by', 'is_active'], name='labs_labtes_created_d702a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False)), fields=('code', 'facility'), name='unique_labtest_code_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False), ('facility__isnull', True)), fields=('code', 'created_by'), name='unique_labtest_code_per_user'),
        ),
    ]
